import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

# The below is the old workflow scripts needed to process this cript
from eval_entry import check_entry
from extract import extract_data_from_volume
from normalize import normalize_volume
from utility import parse_volume_record


INPUT_FILENAME = "SSDA_0024_0034_Gemini_V2.json" # The file generated by Archivault
INSTRUCTIONS_FILENAME = "instructions.json" # The right proimpting instructions for model
TRAINING_DATA_FILENAME = "training_data.json" # Required to run the local script
OUTPUT_FILENAME = "Generated_0024_0034_Gemini_V2.json" # Output of the script

# Metadata to attach to the generated volume record.
RECORD_TYPE = "baptism"
COUNTRY = "United States"
STATE = "Florida"
CITY = "San Agustin"
INSTITUTION = "parish"
TITLE = None  # Change to manual record only if the script is not working 
VOLUME_ID = None  # Change to manual record only if the script is not working 

MATCH_MODE = "or" # 'and' -> exact match filtering
MAX_SHOTS = 1000 # maximum number of few-shot examples allowed
VALIDATE_PARTIALS = False # turn on only when the book often breaks records across page boundaries
TRAINING_KEYWORDS = {"type": RECORD_TYPE, "country": COUNTRY}

# Optional debugging outputs written next to the input file.
SAVE_INTERMEDIATE_VOLUME = False
SAVE_PROCESSED_VOLUME = False
INTERMEDIATE_VOLUME_FILENAME = "split_volume.json"
PROCESSED_VOLUME_FILENAME = "processed_volume.json"
FAILURE_LOG_FILENAME = "failure_log.json"

# This is used for detecting the start of a new baptism entry, might need to change
# if in different language/record type
WEEKDAY_PATTERN = r"(?:Lunes|Martes|Mi[eé]rcoles|Jueves|Viernes|S[áa]bado|Domingo)"
MONTH_PATTERN = r"(?:Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Setiembre|Octubre|Noviembre|Diciembre)"

# Rule used to detect a new record
# line starts with Spanish weekday and somewhere on that line where is either a Spanish moth name

WEEKDAY_RE = re.compile(
    r"\b(Lunes|Martes|Mi[eé]rcoles|Jueves|Viernes|S[áa]bado|Domingo)\b",
    re.IGNORECASE
)

ENTRY_NUMBER_RE = re.compile(r"^\s*\d{1,3}\.\s*$")
ADULT_RE = re.compile(r"^\s*(Adulta|Adulto)\s*$", re.IGNORECASE)
PLUS_WEEKDAY_RE = re.compile(
    r"^\s*\+\s*(Lunes|Martes|Mi[eé]rcoles|Jueves|Viernes|S[áa]bado|Domingo)",
    re.IGNORECASE
)


BASE_DIR = Path(__file__).resolve().parent


def load_transcription_json(json_file_path: Path) -> List[Dict[str, Any]]:
    '''
    Loading Json and verify the top-level object is list
    '''
    with open(json_file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("Expected the input JSON to be a list of items.")
    return data


def infer_volume_id(data: List[Dict[str, Any]], fallback: Optional[int] = None) -> int:
    '''
    determine the volume/book ID, using a manual override if provided
    '''

    if fallback is not None:
        return fallback
    
    for item in data:
        metadata = item.get("metadata", {})
        identifier = metadata.get("identifier")
        if identifier is not None:
            try:
                return int(identifier)
            except (TypeError, ValueError):
                pass

        for image in item.get("images", []):
            file_name = image.get("file", "")
            match = re.match(r"(\d+)-\d+\.jpg$", file_name)
            if match:
                return int(match.group(1))

    raise ValueError("Could not infer volume id from the transcription JSON.")


def infer_title(data: List[Dict[str, Any]], fallback: Optional[str] = None) -> str:
    '''
    determine the title ID, using a manual override if provided
    '''
    
    if fallback:
        return fallback

    for item in data:
        metadata = item.get("metadata", {})
        titles = metadata.get("title")
        if isinstance(titles, list) and titles:
            return str(titles[0])
        if isinstance(titles, str) and titles.strip():
            return titles.strip()

        direct_title = item.get("title")
        if isinstance(direct_title, list) and direct_title:
            return str(direct_title[0])
        if isinstance(direct_title, str) and direct_title.strip():
            return direct_title.strip()

    return "Untitled volume"


def clean_text(text: str) -> str:
    '''
    text cleaning
    '''
    text = text.replace("\r", "")
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    merged: List[str] = []

    for line in lines:
        if not merged:
            merged.append(line)
        elif merged[-1].endswith("-"):
            merged[-1] = merged[-1][:-1] + line
        else:
            merged.append(line)

    return re.sub(r"\s+", " ", " ".join(merged)).strip()


def should_keep_prelude(prelude: str) -> bool:
    '''
    Keep text before first 'real' entry only if satisfy conditions(15 words or 100 char)
    Most of the case it will not keep anything
    '''
    words = prelude.split()
    return len(words) >= 15 or len(prelude) >= 100


def strip_trailing_marginalia(lines: List[str]) -> List[str]:
    '''
    Removed junk text at the end
    '''
    cleaned = [line.rstrip() for line in lines]
    while cleaned and not cleaned[-1].strip():
        cleaned.pop()

    short_run: List[str] = []
    idx = len(cleaned) - 1
    while idx >= 0 and cleaned[idx].strip() and len(cleaned[idx].strip()) <= 30:
        short_run.append(cleaned[idx].strip())
        idx -= 1

    if len(short_run) >= 2:
        return cleaned[: idx + 1]

    if len(short_run) == 1:
        candidate = short_run[0]
        if re.match(r"^\d+[A-Za-z\.]?\s*$", candidate) or re.match(r"^\d+[A-Za-z\.]?\s+.+", candidate):
            return cleaned[: idx + 1]

    return cleaned

# [
#     "Domingo diez y seis de Marzo de mil setecientos noventa y ocho...",
#     "Yo Don Miguel O'Reilly Cura beneficiado bapticé solemnemente...",
#     "fue su madrina Maria Antonia, y lo firmé.",
#     "Miguel Ruiz",-> drop
#     "1094." -> drop
# ]



def split_image_transcription_into_entries(transcription: str) -> List[str]:
    '''
    Converts page-level transcription into multiple entry-level
    '''
    lines = [line.rstrip() for line in transcription.replace("\r", "").splitlines()]
    # split page into lines and finds all lines that look like entry starts
    start_indices = [i for i, line in enumerate(lines) if ENTRY_START_RE.match(line.strip())]

    if not start_indices:
        cleaned = clean_text(transcription)
        return [cleaned] if cleaned else []

    chunks: List[str] = []
    # prelude check
    prelude = clean_text("\n".join(lines[: start_indices[0]]))
    if prelude and should_keep_prelude(prelude):
        chunks.append(prelude)

    for idx, start in enumerate(start_indices):
        # slices
        end = start_indices[idx + 1] if idx + 1 < len(start_indices) else len(lines)
        chunk_lines = strip_trailing_marginalia(lines[start:end])
        chunk = clean_text("\n".join(chunk_lines))
        if chunk:
            chunks.append(chunk)

    return chunks


def build_entry_id(file_name: str, entry_index: int) -> str:
    # 239746-0017.jpg -> stem: 239746-0017, image_id: 0017
    stem = Path(file_name).stem
    image_id = stem.split("-")[-1]
    return f"{image_id}-{entry_index:02d}"


def build_volume_record_from_transcriptions(
    json_file_path: Path,
    volume_id: Optional[int] = None,
    record_type: str = "baptism",
    country: str = "United States",
    state: str = "Florida",
    city: str = "San Agustin",
    institution: str = "parish",
    title: Optional[str] = None,
) -> Dict[str, Any]:
    '''
    converts the uploaded transcription file into the standard volume record format expected downstream
    '''
    data = load_transcription_json(json_file_path)
    volume_id = infer_volume_id(data, fallback=volume_id)
    title = infer_title(data, fallback=title)

    entries: List[Dict[str, str]] = []
    for item in data:
        for image in item.get("images", []):
            transcription = image.get("transcription", "")
            file_name = image.get("file", "")
            if not transcription or not file_name:
                continue

            chunks = split_image_transcription_into_entries(transcription)
            for entry_index, chunk in enumerate(chunks, start=1):
                # Stores {"id": ..., "raw": ...}
                entries.append({"id": build_entry_id(file_name, entry_index), "raw": chunk})

    return {
        "type": record_type,
        "country": country,
        "state": state,
        "city": city,
        "institution": institution,
        "id": volume_id,
        "title": title,
        "entries": entries,
    }


def validate_and_merge_partials(volume_record: Dict[str, Any]) -> Dict[str, Any]:
    '''
    merges adjacent entries if they are split into 2 pages, the 'start' and 'end'
    are labels returned by check_entry
    '''
    entries = [dict(entry) for entry in volume_record["entries"]]
    if not entries:
        return volume_record

    for entry in entries:
        entry["eval"] = check_entry(entry).lower()

    entries_to_delete = set()
    for index in range(len(entries) - 1):
        if "beginning" in entries[index]["eval"] and "end" in entries[index + 1]["eval"]:
            entries[index]["raw"] = f"{entries[index]['raw']} {entries[index + 1]['raw']}".strip()
            entries_to_delete.add(index + 1)

    merged_entries = [
        entry
        for index, entry in enumerate(entries)
        if index not in entries_to_delete and "end" not in entry["eval"]
    ]
    for entry in merged_entries:
        entry.pop("eval", None)

    updated = dict(volume_record)
    updated["entries"] = merged_entries
    return updated


def save_json(data: Dict[str, Any], output_path: Path) -> None:
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def convert_processed_volume_to_training_data(processed_volume: Dict[str, Any]) -> Dict[str, Any]:
    '''
    Convert to final schema
    '''
    parsed_volume, volume_metadata = parse_volume_record(processed_volume)
    language = volume_metadata["language"]

    examples: List[Dict[str, Any]] = []
    for entry in processed_volume.get("entries", []):
        examples.append(
            {
                "type": volume_metadata.get("type", ""),
                "language": language,
                "country": parsed_volume.get("country", ""),
                "state": volume_metadata.get("state", ""),
                "city": parsed_volume.get("city", ""),
                "institution": volume_metadata.get("institution", ""),
                "id": volume_metadata.get("id", ""),
                "entry": entry.get("id", ""),
                "raw": entry.get("raw", ""),
                "normalized": entry.get("normalized", ""),
                "data": entry.get("data", {}),
            }
        )

    return {"examples": examples}


def ensure_required_file(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Missing {label}: {path}")

# transcription JSON -> volume record -> optional merge -> normalization -> extraction 
# -> final examples JSON
def run_pipeline() -> Path:
    '''
    Main workflow function
    '''
    input_path = BASE_DIR / INPUT_FILENAME
    instructions_path = BASE_DIR / INSTRUCTIONS_FILENAME
    training_data_path = BASE_DIR / TRAINING_DATA_FILENAME
    output_path = BASE_DIR / OUTPUT_FILENAME
    failure_log_path = BASE_DIR / FAILURE_LOG_FILENAME
    # 3 required files
    ensure_required_file(input_path, "input transcription JSON")
    ensure_required_file(instructions_path, "instructions file")
    ensure_required_file(training_data_path, "training data file")

    volume_record = build_volume_record_from_transcriptions(
        json_file_path=input_path,
        volume_id=VOLUME_ID,
        record_type=RECORD_TYPE,
        country=COUNTRY,
        state=STATE,
        city=CITY,
        institution=INSTITUTION,
        title=TITLE,
    )

    if VALIDATE_PARTIALS:
        volume_record = validate_and_merge_partials(volume_record)

    if SAVE_INTERMEDIATE_VOLUME:
        save_json(volume_record, BASE_DIR / INTERMEDIATE_VOLUME_FILENAME)

    normalized_volume = normalize_volume(
        volume_record,
        str(instructions_path),
        str(training_data_path),
        keywords=TRAINING_KEYWORDS,
        match_mode=MATCH_MODE,
        max_shots=MAX_SHOTS,
    )

    processed_volume = extract_data_from_volume(
        normalized_volume,
        str(instructions_path),
        str(training_data_path),
        keywords=TRAINING_KEYWORDS,
        match_mode=MATCH_MODE,
        max_shots=MAX_SHOTS,
        output_path=str(BASE_DIR / PROCESSED_VOLUME_FILENAME) if SAVE_PROCESSED_VOLUME else None,
        log_path=str(failure_log_path),
    )

    training_data = convert_processed_volume_to_training_data(processed_volume)
    save_json(training_data, output_path)
    return output_path


def main() -> None:
    output_path = run_pipeline()
    print(f"Done. Output written to: {output_path}")


if __name__ == "__main__":
    main()
